### ISSUE TITLE
Timeout opening VIM connection

### ISSUE THREAD

**Issue by jcam** [rlane/rbvmomi#14]
In the process of getting chef/knife/vsphere working, I discovered that I was getting network timeout errors when trying to open the VIM vserver connection.
Currently the open_timeout is set to 5, increasing to 500 cleared the issue.
On my system there is a 3 or 4 second delay just from doing the DNS lookup, but regardless, 5 secs seems rather aggressive for a hard-coded value that cannot be overridden through options/arguments.

Can/should this value be increased?

```
rbvmomi/trivial_soap.rb
52c52
<     @http.open_timeout = 5

---
>     @http.open_timeout = 60
```

**Comment by cdickmann** [comment]
500 seems rather high. Users want to get feedback sooner than later if connection setup fails. Maybe we can go to 10 seconds, but if connect takes longer than 10 seconds, we are remote controlling a vsphere on its way to Mars.

**Comment by jcam** [comment]
i think 30 or 60 secs is pretty standard timeout for things like opening an ssh connection... i agree 500 is probably too high, but even 10 may be too short for some instances... it would be nice to be able to override the timeout in the config, though...
(updated diff)
