### ISSUE TITLE
:insecure option gives Invalid argument (Errno::EINVAL) error

### ISSUE THREAD

**Issue by tommasop** [rlane/rbvmomi#2]
Environment:
OS Snow Leopard
Ruby Version 1.9.2-p180 (with RVM)

Steps to replicate issue:
launch example readme-1.rb with --insecure option

Error:

/Users/tommasop/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/net/protocol.rb:137:in `select': Invalid argument (Errno::EINVAL)
    from /Users/tommasop/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/net/protocol.rb:137:in`rescue in rbuf_fill'
    from /Users/tommasop/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/net/protocol.rb:134:in `rbuf_fill'
    from /Users/tommasop/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/net/protocol.rb:116:in`readuntil'
    from /Users/tommasop/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/net/protocol.rb:126:in `readline'
    from /Users/tommasop/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/net/http.rb:2219:in`read_status_line'
    from /Users/tommasop/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/net/http.rb:2208:in `read_new'
    from /Users/tommasop/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/net/http.rb:1191:in`transport_request'
    from /Users/tommasop/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/net/http.rb:1177:in `request'
    from /Users/tommasop/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/net/http.rb:1125:in`request_post'
    from /Users/tommasop/.rvm/gems/ruby-1.9.2-p180/gems/rbvmomi-1.1.6/lib/rbvmomi/trivial_soap.rb:73:in `block in request'
    from <internal:prelude>:10:in`synchronize'
    from /Users/tommasop/.rvm/gems/ruby-1.9.2-p180/gems/rbvmomi-1.1.6/lib/rbvmomi/trivial_soap.rb:71:in `request'
    from /Users/tommasop/.rvm/gems/ruby-1.9.2-p180/gems/rbvmomi-1.1.6/lib/rbvmomi/connection.rb:64:in`call'
    from /Users/tommasop/.rvm/gems/ruby-1.9.2-p180/gems/rbvmomi-1.1.6/lib/rbvmomi/basic_types.rb:172:in `_call'
    from /Users/tommasop/.rvm/gems/ruby-1.9.2-p180/gems/rbvmomi-1.1.6/lib/rbvmomi/basic_types.rb:70:in`block (2 levels) in init'
    from /Users/tommasop/.rvm/gems/ruby-1.9.2-p180/gems/rbvmomi-1.1.6/lib/rbvmomi/vim.rb:50:in `serviceContent'
    from /Users/tommasop/.rvm/gems/ruby-1.9.2-p180/gems/rbvmomi-1.1.6/lib/rbvmomi/vim.rb:34:in`block in connect'
    from /Users/tommasop/.rvm/gems/ruby-1.9.2-p180/gems/rbvmomi-1.1.6/lib/rbvmomi/vim.rb:33:in `tap'
    from /Users/tommasop/.rvm/gems/ruby-1.9.2-p180/gems/rbvmomi-1.1.6/lib/rbvmomi/vim.rb:33:in`connect'
    from readme-1.rb:32:in `<main>'

**Comment by rlane** [comment]
Could you send me the strace (or OS X equivalent) output? The long timeout to select(2) is a likely culprit, so please try changing lib/rbvmomi/trivial_soap.rb:38 (@http.read_timeout) to a smaller number.

**Comment by tommasop** [comment]
Correct! I modified the @http.read_timeout dropping three zeroes and it
worked flawlessly

Thanks

On Tue, Mar 15, 2011 at 4:28 PM, rlane <
reply@reply.github.com>wrote:

> Could you send me the strace (or OS X equivalent) output? The long timeout
> to select(2) is a likely culprit, so please try changing
> lib/rbvmomi/trivial_soap.rb:38 (@http.read_timeout) to a smaller number.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rlane/rbvmomi/issues/2#comment_876604

## 

IN OBSCURO MIRANDA RELUCENT

**Comment by rlane** [comment]
Released in 1.1.18.
