### ISSUE TITLE
guestOperationsManager managed object

### ISSUE THREAD

**Issue by m4rco-** [rlane/rbvmomi#6]
Hi, 
Reading the vSphere API 5.0 doc, the guestOperationsManager should be accessed by the ServiceContent class. 
However, when I try to invoke it , it returns me "nil"

om = vim.serviceContent.guestOperationsManager
=> nil

(I'm already doing tasks like poweron/snapshot/etc and everything works fine)

I'm trying to figure out how to execute a program inside a windows VM, and reading the APIs it seems that guestOperationsManager should do what I'm looking for....

...any clues?

thank you in advance.

m.

**Comment by rlane** [comment]
What's the value of vim.rev? Can you paste the code you're using?

**Comment by m4rco-** [comment]
The value of vim.rev is 4.1 , does it mean that i'm not using the 5.0 APIs? I've just installed the rbvmomi gem, did I miss something?

the cose is this one:

require 'rubygems'
require 'rbvmomi'
vim = RbVmomi::VIM.connect(:host => '10.10.10.10', :user => 'root', :password=> 'password', :insecure => true)
dc = vim.serviceInstance.find_datacenter
vm = dc.find_vm("WinXPSP3")

thank you.

**Comment by m4rco-** [comment]
Ops, I just figured out that I was trying to use the gem with an ESXi 4.1 server :\
Now I just updated it to 5.1, and when I call  vim.serviceContent.guestOperationsManager it correctly returns me that object. 
I'm going to try it, if I get success, i'm looking forward to posting the full example here.
thank you!

**Comment by m4rco-** [comment]
Ok here is the new problem: 
When I try to authenticate to the guest system, I have this error:

om = vim.serviceContent.guestOperationsManager 
am = om.authManager
guestauth = {:interactiveSession => false, :username => 'admin', :password => 'password'}
am.ValidateCredentialsInGuest(:vm => vm, :auth => guestauth)
RuntimeError: unexpected property name username

Now, standing to the API,  guestauth should be considered as a NamePasswordAuthentication Data Object, which is an extension of GuestAuthentication one.  However, when I'm calling am.ValidateCredentialsInGuest it is expecting only the :interactiveSession attribute inside the auth value.
What I mean, is that it seems to be not able to read the extended attributes of NamePasswordAuthentication...

any clues?

thx you

**Comment by rlane** [comment]
Excerpts from m4rco-'s message of 2011-10-14 07:53:50 -0400:

> Ok here is the new problem: 
> When I try to authenticate to the guest system, I have this error:
> 
> om = vim.serviceContent.guestOperationsManager 
> am = om.authManager
> guestauth = {:interactiveSession => false, :username => 'admin', :password => 'password'}
> am.ValidateCredentialsInGuest(:vm => vm, :auth => guestauth)
> RuntimeError: unexpected property name username
> 
> Now, standing to the API,  guestauth should be considered as a NamePasswordAuthentication Data Object, which is an extension of GuestAuthentication one.  However, when I'm calling am.ValidateCredentialsInGuest it is expecting only the :interactiveSession attribute inside the auth value.
> What I mean, is that it seems to be not able to read the extended attributes of NamePasswordAuthentication...

In the case of subtyping you need to explicitly create the data object.
Just do RbVmomi::VIM::NamePasswordAuthentication(:interactiveSession => false, ...).
I usually "include RbVmomi" to make that shorter.

**Comment by m4rco-** [comment]
Thank you rlane, it works!
soon i'll post here my code,

bye!

m.
